CREATE OR REPLACE TABLE MARTS.MART_INVENTORY_HEALTH AS
SELECT SNAPSHOT_DATE, STORE_ID, PRODUCT_ID,
       SUM(QUANTITY_ON_HAND) QUANTITY_ON_HAND,
       SUM(INVENTORY_VALUE) INVENTORY_VALUE,
       SUM(IFF(EXPIRY_DATE BETWEEN SNAPSHOT_DATE AND DATEADD(day,7,SNAPSHOT_DATE),QUANTITY_ON_HAND,0)) EXPIRING_UNITS_7D,
       SUM(IFF(EXPIRY_DATE BETWEEN SNAPSHOT_DATE AND DATEADD(day,7,SNAPSHOT_DATE),INVENTORY_VALUE,0)) EXPIRING_INVENTORY_VALUE_7D
FROM CURATED.FACT_INVENTORY_SNAPSHOT GROUP BY SNAPSHOT_DATE,STORE_ID,PRODUCT_ID;

CREATE OR REPLACE TABLE MARTS.MART_EXPIRY_RISK AS
SELECT * FROM MARTS.MART_INVENTORY_HEALTH WHERE EXPIRING_UNITS_7D>0;

CREATE OR REPLACE TABLE MARTS.MART_WASTE_PERFORMANCE AS
SELECT WASTE_DATE, BATCH_ID, WASTE_REASON, SUM(QUANTITY_WASTED) QUANTITY_WASTED,
       SUM(ESTIMATED_LOSS) ESTIMATED_LOSS
FROM CURATED.FACT_WASTE GROUP BY WASTE_DATE,BATCH_ID,WASTE_REASON;

CREATE OR REPLACE TABLE MARTS.MART_CAMPAIGN_PERFORMANCE AS
SELECT EVENT_DATE,CAMPAIGN_ID,PRODUCT_ID,STORE_ID,AUDIENCE_ID,REGION,CHANNEL,DEVICE,
       IMPRESSIONS,CLICKS,CONVERSIONS,SPEND,ATTRIBUTED_REVENUE,
       CLICKS/NULLIF(IMPRESSIONS,0) CTR,
       SPEND*1000/NULLIF(IMPRESSIONS,0) CPM,
       SPEND/NULLIF(CLICKS,0) CPC,
       SPEND/NULLIF(CONVERSIONS,0) CPA,
       ATTRIBUTED_REVENUE/NULLIF(SPEND,0) ROAS,
       LATEST_INGESTED_AT
FROM CURATED.FACT_CAMPAIGN_DAILY;

CREATE OR REPLACE TABLE MARTS.MART_CAMPAIGN_PACING AS
SELECT CAMPAIGN_ID,MIN(EVENT_DATE) FIRST_ACTIVITY_DATE,MAX(EVENT_DATE) LAST_ACTIVITY_DATE,
       SUM(SPEND) ACTUAL_SPEND,SUM(ATTRIBUTED_REVENUE) ATTRIBUTED_REVENUE,
       SUM(CONVERSIONS) CONVERSIONS
FROM CURATED.FACT_CAMPAIGN_DAILY GROUP BY CAMPAIGN_ID;

CREATE OR REPLACE TABLE MARTS.MART_PROMOTED_PRODUCT_RISK AS
SELECT c.EVENT_DATE,c.CAMPAIGN_ID,c.PRODUCT_ID,c.STORE_ID,c.SPEND,c.ATTRIBUTED_REVENUE,
       c.ATTRIBUTED_REVENUE/NULLIF(c.SPEND,0) ROAS,
       i.QUANTITY_ON_HAND,i.EXPIRING_UNITS_7D,
       IFF(COALESCE(i.QUANTITY_ON_HAND,0)<20,TRUE,FALSE) LOW_STOCK_FLAG,
       IFF(COALESCE(i.EXPIRING_UNITS_7D,0)>0,TRUE,FALSE) EXPIRY_RISK_FLAG
FROM MARTS.MART_CAMPAIGN_PERFORMANCE c
LEFT JOIN MARTS.MART_INVENTORY_HEALTH i
  ON i.SNAPSHOT_DATE=c.EVENT_DATE AND TO_VARCHAR(i.PRODUCT_ID)=c.PRODUCT_ID AND TO_VARCHAR(i.STORE_ID)=c.STORE_ID;

CREATE OR REPLACE TABLE MARTS.MART_PIPELINE_HEALTH AS
SELECT r.RUN_ID,r.DAG_ID,r.BUSINESS_DATE,r.STARTED_AT,r.FINISHED_AT,r.STATUS,r.ROWS_PROCESSED,
       COUNT_IF(q.STATUS='FAIL') FAILED_CHECKS,COUNT_IF(q.STATUS='WARN') WARNING_CHECKS
FROM CURATED.FACT_PIPELINE_RUN r LEFT JOIN CURATED.FACT_DATA_QUALITY_RESULT q ON q.RUN_ID=r.RUN_ID
GROUP BY r.RUN_ID,r.DAG_ID,r.BUSINESS_DATE,r.STARTED_AT,r.FINISHED_AT,r.STATUS,r.ROWS_PROCESSED;
