CREATE TABLE IF NOT EXISTS CURATED.DIM_DATE (
  DATE_KEY NUMBER PRIMARY KEY, FULL_DATE DATE, YEAR NUMBER, QUARTER NUMBER,
  MONTH NUMBER, MONTH_NAME STRING, WEEK_OF_YEAR NUMBER, DAY_OF_MONTH NUMBER, DAY_NAME STRING
);
MERGE INTO CURATED.DIM_DATE t USING (
  SELECT TO_NUMBER(TO_CHAR(d,'YYYYMMDD')) DATE_KEY, d FULL_DATE,
         YEAR(d) YEAR, QUARTER(d) QUARTER, MONTH(d) MONTH, MONTHNAME(d) MONTH_NAME,
         WEEKOFYEAR(d) WEEK_OF_YEAR, DAY(d) DAY_OF_MONTH, DAYNAME(d) DAY_NAME
  FROM (
    SELECT DATEADD(day, SEQ4(), '2024-01-01'::DATE) d FROM TABLE(GENERATOR(ROWCOUNT=>1827))
  )
) s ON t.DATE_KEY=s.DATE_KEY
WHEN MATCHED THEN UPDATE ALL BY NAME
WHEN NOT MATCHED THEN INSERT ALL BY NAME;

CREATE TABLE IF NOT EXISTS CURATED.DIM_STORE (
  STORE_KEY NUMBER AUTOINCREMENT, STORE_ID NUMBER, STORE_NAME STRING, CITY STRING, ADDRESS STRING,
  UNIQUE(STORE_ID)
);
MERGE INTO CURATED.DIM_STORE t USING RAW.RAW_STORES s ON t.STORE_ID=s.ID
WHEN MATCHED THEN UPDATE SET STORE_NAME=s.NAME,CITY=s.CITY,ADDRESS=s.ADDRESS
WHEN NOT MATCHED THEN INSERT(STORE_ID,STORE_NAME,CITY,ADDRESS) VALUES(s.ID,s.NAME,s.CITY,s.ADDRESS);

CREATE TABLE IF NOT EXISTS CURATED.DIM_SUPPLIER (
  SUPPLIER_KEY NUMBER AUTOINCREMENT, SUPPLIER_ID NUMBER, SUPPLIER_NAME STRING,
  COUNTRY STRING, CONTACT_EMAIL STRING, UNIQUE(SUPPLIER_ID)
);
MERGE INTO CURATED.DIM_SUPPLIER t USING RAW.RAW_SUPPLIERS s ON t.SUPPLIER_ID=s.ID
WHEN MATCHED THEN UPDATE SET SUPPLIER_NAME=s.NAME,COUNTRY=s.COUNTRY,CONTACT_EMAIL=s.CONTACT_EMAIL
WHEN NOT MATCHED THEN INSERT(SUPPLIER_ID,SUPPLIER_NAME,COUNTRY,CONTACT_EMAIL) VALUES(s.ID,s.NAME,s.COUNTRY,s.CONTACT_EMAIL);

CREATE TABLE IF NOT EXISTS CURATED.DIM_PRODUCT (
  PRODUCT_KEY NUMBER AUTOINCREMENT, PRODUCT_ID NUMBER, SKU STRING, PRODUCT_NAME STRING,
  CATEGORY STRING, ORIGIN_COUNTRY STRING, SUPPLIER_ID NUMBER, UNIT_COST NUMBER(18,2), UNIQUE(SKU)
);
MERGE INTO CURATED.DIM_PRODUCT t USING STAGING.STG_PRODUCTS s ON t.SKU=s.SKU
WHEN MATCHED THEN UPDATE SET PRODUCT_ID=s.ID,PRODUCT_NAME=s.NAME_EN,CATEGORY=s.CATEGORY,
  ORIGIN_COUNTRY=s.ORIGIN_COUNTRY,SUPPLIER_ID=s.SUPPLIER_ID,UNIT_COST=s.UNIT_COST
WHEN NOT MATCHED THEN INSERT(PRODUCT_ID,SKU,PRODUCT_NAME,CATEGORY,ORIGIN_COUNTRY,SUPPLIER_ID,UNIT_COST)
  VALUES(s.ID,s.SKU,s.NAME_EN,s.CATEGORY,s.ORIGIN_COUNTRY,s.SUPPLIER_ID,s.UNIT_COST);

CREATE TABLE IF NOT EXISTS CURATED.DIM_ADVERTISER (
  ADVERTISER_KEY NUMBER AUTOINCREMENT, ADVERTISER_ID STRING, ADVERTISER_NAME STRING, INDUSTRY STRING,
  UNIQUE(ADVERTISER_ID)
);
CREATE TABLE IF NOT EXISTS CURATED.DIM_CAMPAIGN (
  CAMPAIGN_KEY NUMBER AUTOINCREMENT, CAMPAIGN_ID STRING, CAMPAIGN_CODE STRING,
  ADVERTISER_ID STRING, CHANNEL STRING, OBJECTIVE STRING, START_DATE DATE, END_DATE DATE,
  PLANNED_BUDGET NUMBER(18,2), DAILY_BUDGET NUMBER(18,2), STATUS STRING, UNIQUE(CAMPAIGN_ID)
);
CREATE TABLE IF NOT EXISTS CURATED.DIM_CHANNEL (
  CHANNEL_KEY NUMBER AUTOINCREMENT, CHANNEL STRING, UNIQUE(CHANNEL)
);
MERGE INTO CURATED.DIM_CHANNEL t USING (SELECT DISTINCT CHANNEL FROM STAGING.STG_CAMPAIGN_EVENTS WHERE CHANNEL IS NOT NULL) s
ON t.CHANNEL=s.CHANNEL WHEN NOT MATCHED THEN INSERT(CHANNEL) VALUES(s.CHANNEL);
CREATE TABLE IF NOT EXISTS CURATED.DIM_AUDIENCE (
  AUDIENCE_KEY NUMBER AUTOINCREMENT, AUDIENCE_ID STRING, AUDIENCE_NAME STRING, UNIQUE(AUDIENCE_ID)
);
