CREATE TABLE IF NOT EXISTS CURATED.FACT_INVENTORY_SNAPSHOT (
  SNAPSHOT_DATE DATE, STORE_ID NUMBER, PRODUCT_ID NUMBER, BATCH_ID NUMBER,
  QUANTITY_ON_HAND NUMBER, EXPIRY_DATE DATE, UNIT_COST NUMBER(18,2), INVENTORY_VALUE NUMBER(18,2),
  PRIMARY KEY (SNAPSHOT_DATE, STORE_ID, PRODUCT_ID, BATCH_ID)
);
MERGE INTO CURATED.FACT_INVENTORY_SNAPSHOT t USING (
  SELECT CURRENT_DATE() SNAPSHOT_DATE, i.STORE_ID, i.PRODUCT_ID, i.ID BATCH_ID,
         i.QUANTITY QUANTITY_ON_HAND, i.EXPIRY_DATE, p.UNIT_COST,
         i.QUANTITY*p.UNIT_COST INVENTORY_VALUE
  FROM STAGING.STG_INVENTORY i JOIN STAGING.STG_PRODUCTS p ON p.ID=i.PRODUCT_ID
) s ON t.SNAPSHOT_DATE=s.SNAPSHOT_DATE AND t.BATCH_ID=s.BATCH_ID
WHEN MATCHED THEN UPDATE ALL BY NAME WHEN NOT MATCHED THEN INSERT ALL BY NAME;

CREATE TABLE IF NOT EXISTS CURATED.FACT_INVENTORY_MOVEMENT (
  MOVEMENT_ID NUMBER PRIMARY KEY, BATCH_ID NUMBER, MOVEMENT_TYPE STRING,
  QUANTITY_CHANGE NUMBER, REASON STRING, CREATED_AT TIMESTAMP_NTZ
);
MERGE INTO CURATED.FACT_INVENTORY_MOVEMENT t USING RAW.RAW_INVENTORY_MOVEMENTS s ON t.MOVEMENT_ID=s.ID
WHEN MATCHED THEN UPDATE SET BATCH_ID=s.BATCH_ID,MOVEMENT_TYPE=s.MOVEMENT_TYPE,
 QUANTITY_CHANGE=s.QUANTITY_CHANGE,REASON=s.REASON,CREATED_AT=s.CREATED_AT
WHEN NOT MATCHED THEN INSERT VALUES(s.ID,s.BATCH_ID,s.MOVEMENT_TYPE,s.QUANTITY_CHANGE,s.REASON,s.CREATED_AT);

CREATE TABLE IF NOT EXISTS CURATED.FACT_WASTE (
  WASTE_ID NUMBER PRIMARY KEY, BATCH_ID NUMBER, QUANTITY_WASTED NUMBER,
  WASTE_REASON STRING, WASTE_DATE DATE, ESTIMATED_LOSS NUMBER(18,2)
);
MERGE INTO CURATED.FACT_WASTE t USING STAGING.STG_WASTE s ON t.WASTE_ID=s.ID
WHEN MATCHED THEN UPDATE SET BATCH_ID=s.BATCH_ID,QUANTITY_WASTED=s.QUANTITY_WASTED,
 WASTE_REASON=s.WASTE_REASON,WASTE_DATE=s.WASTE_DATE,ESTIMATED_LOSS=s.ESTIMATED_LOSS
WHEN NOT MATCHED THEN INSERT VALUES(s.ID,s.BATCH_ID,s.QUANTITY_WASTED,s.WASTE_REASON,s.WASTE_DATE,s.ESTIMATED_LOSS);

CREATE TABLE IF NOT EXISTS CURATED.FACT_CAMPAIGN_DAILY (
  EVENT_DATE DATE, CAMPAIGN_ID STRING, PRODUCT_ID STRING, STORE_ID STRING,
  AUDIENCE_ID STRING, REGION STRING, CHANNEL STRING, DEVICE STRING,
  IMPRESSIONS NUMBER, CLICKS NUMBER, CONVERSIONS NUMBER, SPEND NUMBER(18,4),
  ATTRIBUTED_REVENUE NUMBER(18,4), LATEST_INGESTED_AT TIMESTAMP_TZ,
  PRIMARY KEY(EVENT_DATE,CAMPAIGN_ID,PRODUCT_ID,STORE_ID,AUDIENCE_ID,CHANNEL,DEVICE)
);
MERGE INTO CURATED.FACT_CAMPAIGN_DAILY t USING (
  SELECT EVENT_DATE,CAMPAIGN_EXTERNAL_ID CAMPAIGN_ID,PRODUCT_EXTERNAL_ID PRODUCT_ID,
    STORE_EXTERNAL_ID STORE_ID,AUDIENCE_EXTERNAL_ID AUDIENCE_ID,REGION,CHANNEL,DEVICE,
    SUM(IMPRESSIONS) IMPRESSIONS,SUM(CLICKS) CLICKS,SUM(CONVERSIONS) CONVERSIONS,
    SUM(SPEND) SPEND,SUM(ATTRIBUTED_REVENUE) ATTRIBUTED_REVENUE,MAX(INGESTED_AT) LATEST_INGESTED_AT
  FROM STAGING.STG_CAMPAIGN_EVENTS
  GROUP BY ALL
) s ON t.EVENT_DATE=s.EVENT_DATE AND t.CAMPAIGN_ID=s.CAMPAIGN_ID
 AND COALESCE(t.PRODUCT_ID,'')=COALESCE(s.PRODUCT_ID,'') AND COALESCE(t.STORE_ID,'')=COALESCE(s.STORE_ID,'')
 AND COALESCE(t.AUDIENCE_ID,'')=COALESCE(s.AUDIENCE_ID,'') AND t.CHANNEL=s.CHANNEL AND t.DEVICE=s.DEVICE
WHEN MATCHED THEN UPDATE ALL BY NAME WHEN NOT MATCHED THEN INSERT ALL BY NAME;

CREATE TABLE IF NOT EXISTS CURATED.FACT_CONVERSION (
  CONVERSION_ID STRING PRIMARY KEY, EVENT_DATE DATE, CAMPAIGN_ID STRING,
  PRODUCT_ID STRING, STORE_ID STRING, CONVERSION_TYPE STRING,
  CONVERSION_VALUE NUMBER(18,4), ATTRIBUTED_REVENUE NUMBER(18,4)
);
CREATE TABLE IF NOT EXISTS CURATED.FACT_PIPELINE_RUN (
  RUN_ID STRING PRIMARY KEY, DAG_ID STRING, BUSINESS_DATE DATE, STARTED_AT TIMESTAMP_TZ,
  FINISHED_AT TIMESTAMP_TZ, STATUS STRING, ROWS_PROCESSED NUMBER, ERROR_MESSAGE STRING
);
CREATE TABLE IF NOT EXISTS CURATED.FACT_DATA_QUALITY_RESULT (
  RUN_ID STRING, BUSINESS_DATE DATE, CHECK_NAME STRING, OBSERVED_VALUE NUMBER,
  STATUS STRING, CHECKED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY(RUN_ID,CHECK_NAME)
);
