SELECT IFF(COUNT(*)>0,1,0) AS PASS FROM MARTS.MART_INVENTORY_HEALTH;
SELECT IFF(COUNT_IF(CLICKS>IMPRESSIONS)=0,1,0) AS PASS FROM MARTS.MART_CAMPAIGN_PERFORMANCE;
SELECT IFF(COUNT_IF(CONVERSIONS>CLICKS)=0,1,0) AS PASS FROM MARTS.MART_CAMPAIGN_PERFORMANCE;
SELECT IFF(COUNT_IF(SPEND<0)=0,1,0) AS PASS FROM MARTS.MART_CAMPAIGN_PERFORMANCE;
SELECT IFF(MAX(LATEST_INGESTED_AT)>=DATEADD(hour,-36,CURRENT_TIMESTAMP()),1,0) AS PASS
FROM MARTS.MART_CAMPAIGN_PERFORMANCE;
