CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS MARTS;
CREATE FILE FORMAT IF NOT EXISTS RAW.ANALYTICS_PARQUET TYPE=PARQUET;
CREATE STAGE IF NOT EXISTS RAW.ANALYTICS_STAGE FILE_FORMAT=RAW.ANALYTICS_PARQUET;
