CREATE TABLE IF NOT EXISTS STAGING.STG_PRODUCTS LIKE RAW.RAW_PRODUCTS;
MERGE INTO STAGING.STG_PRODUCTS t USING (
  SELECT * FROM RAW.RAW_PRODUCTS QUALIFY ROW_NUMBER() OVER (PARTITION BY SKU ORDER BY CREATED_AT DESC NULLS LAST)=1
) s ON t.SKU=s.SKU
WHEN MATCHED THEN UPDATE ALL BY NAME
WHEN NOT MATCHED THEN INSERT ALL BY NAME;

CREATE TABLE IF NOT EXISTS STAGING.STG_INVENTORY LIKE RAW.RAW_INVENTORY_BATCHES;
MERGE INTO STAGING.STG_INVENTORY t USING (
  SELECT * FROM RAW.RAW_INVENTORY_BATCHES QUALIFY ROW_NUMBER() OVER (PARTITION BY BATCH_CODE ORDER BY CREATED_AT DESC NULLS LAST)=1
) s ON t.BATCH_CODE=s.BATCH_CODE
WHEN MATCHED THEN UPDATE ALL BY NAME
WHEN NOT MATCHED THEN INSERT ALL BY NAME;

CREATE TABLE IF NOT EXISTS STAGING.STG_WASTE LIKE RAW.RAW_WASTE_RECORDS;
MERGE INTO STAGING.STG_WASTE t USING RAW.RAW_WASTE_RECORDS s ON t.ID=s.ID
WHEN MATCHED THEN UPDATE ALL BY NAME
WHEN NOT MATCHED THEN INSERT ALL BY NAME;

CREATE TABLE IF NOT EXISTS STAGING.STG_CAMPAIGN_EVENTS LIKE RAW.RAW_CAMPAIGN_EVENTS;
MERGE INTO STAGING.STG_CAMPAIGN_EVENTS t USING (
  SELECT * FROM RAW.RAW_CAMPAIGN_EVENTS QUALIFY ROW_NUMBER() OVER (PARTITION BY EVENT_ID ORDER BY INGESTED_AT DESC NULLS LAST)=1
) s ON t.EVENT_ID=s.EVENT_ID
WHEN MATCHED THEN UPDATE ALL BY NAME
WHEN NOT MATCHED THEN INSERT ALL BY NAME;
