CREATE TABLE IF NOT EXISTS RAW.RAW_PRODUCTS (
  ID NUMBER, SKU STRING, NAME_EN STRING, NAME_ZH STRING, CATEGORY STRING,
  ORIGIN_COUNTRY STRING, SUPPLIER_ID NUMBER, UNIT_COST NUMBER(18,2), CREATED_AT TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS RAW.RAW_STORES (
  ID NUMBER, NAME STRING, CITY STRING, ADDRESS STRING, CREATED_AT TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS RAW.RAW_SUPPLIERS (
  ID NUMBER, NAME STRING, COUNTRY STRING, CONTACT_EMAIL STRING, CREATED_AT TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS RAW.RAW_INVENTORY_BATCHES (
  ID NUMBER, PRODUCT_ID NUMBER, STORE_ID NUMBER, BATCH_CODE STRING, QUANTITY NUMBER,
  EXPIRY_DATE DATE, RECEIVED_DATE DATE, CREATED_AT TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS RAW.RAW_INVENTORY_MOVEMENTS (
  ID NUMBER, BATCH_ID NUMBER, MOVEMENT_TYPE STRING, QUANTITY_CHANGE NUMBER,
  REASON STRING, CREATED_AT TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS RAW.RAW_WASTE_RECORDS (
  ID NUMBER, BATCH_ID NUMBER, QUANTITY_WASTED NUMBER, WASTE_REASON STRING,
  WASTE_DATE DATE, ESTIMATED_LOSS NUMBER(18,2)
);
CREATE TABLE IF NOT EXISTS RAW.RAW_CAMPAIGN_EVENTS (
  EVENT_ID STRING, EVENT_DATE DATE, CAMPAIGN_EXTERNAL_ID STRING,
  PRODUCT_EXTERNAL_ID STRING, STORE_EXTERNAL_ID STRING, AUDIENCE_EXTERNAL_ID STRING,
  REGION STRING, CHANNEL STRING, DEVICE STRING, IMPRESSIONS NUMBER, CLICKS NUMBER,
  CONVERSIONS NUMBER, SPEND NUMBER(18,4), ATTRIBUTED_REVENUE NUMBER(18,4),
  INGESTED_AT TIMESTAMP_TZ, PROCESSING_DATE DATE
);
