apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-inventory-config
  namespace: smart-inventory
  labels:
    app.kubernetes.io/name: smart-inventory-erp
    app.kubernetes.io/part-of: smart-inventory-erp
data:
  NODE_ENV: "production"

  BACKEND_PORT: "5001"
  FRONTEND_PORT: "3000"
  PHP_PORT: "8000"

  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "smart_inventory_erp"
  DB_USER: "root"

  PHP_SERVICE_URL: "http://legacy-php:8000"

  SERVER_API_BASE_URL: "http://backend:5001"
  NEXT_PUBLIC_API_BASE_URL: "http://localhost:5001"