apiVersion: v1
kind: Namespace
metadata:
  name: smart-inventory
  labels:
    app.kubernetes.io/name: smart-inventory-erp
    app.kubernetes.io/part-of: smart-inventory-erp
    app.kubernetes.io/managed-by: kubectl