apiVersion: v1
kind: Secret
metadata:
  name: smart-inventory-secret
  namespace: smart-inventory
  labels:
    app.kubernetes.io/name: smart-inventory-erp
    app.kubernetes.io/part-of: smart-inventory-erp
type: Opaque
stringData:
  DB_PASSWORD: "abc123456"
  MYSQL_ROOT_PASSWORD: "abc123456"
  JWT_SECRET: "smart_inventory_demo_secret_change_later"